# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudworkstation < Formula
  desc "CLI tool for launching pre-configured cloud workstations for academic research"
  homepage "https://github.com/scttfrdmn/cloudworkstation"
  version "0.5.4"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.4/cloudworkstation_0.5.4_darwin_x86_64.tar.gz"
      sha256 "637857c0bbde86b5caed0659ee6ecb11febdaabbd1182cd8a10cd18e96cd50b3"

      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.4/cloudworkstation_0.5.4_darwin_arm64.tar.gz"
      sha256 "e75160d1662b70d083081bae0e981a4c3cf0c4a1d5c12467e3f8ebd0f134cf74"

      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.4/cloudworkstation_0.5.4_linux_x86_64.tar.gz"
      sha256 "73ff4c402e9bed54b66a7c9d94a28264b3085471f2f444512dbf8e643bcbde05"
      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.4/cloudworkstation_0.5.4_linux_arm64.tar.gz"
      sha256 "5ed23f6798eea8239440d9952d1449dd3f965670a6b5df0093a588e21b42d545"
      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
  end

  def caveats
    <<~EOS
      CloudWorkstation has been installed!

      Command Line Interface (CLI):
        cws --help

      Terminal User Interface (TUI):
        cws tui

      Quick start:
        cws templates                           # List available templates
        cws launch <template-name> <instance>   # Launch a workstation

      The daemon (cwsd) starts automatically when needed - no manual setup required!

      AWS credentials are required:
        aws configure

      Documentation: https://github.com/scttfrdmn/cloudworkstation
    EOS
  end

  test do
    system "#{bin}/cws", "--version"
    system "#{bin}/cwsd", "--version"
  end
end
