# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prism < Formula
  desc "CLI tool for launching pre-configured cloud workstations for academic research"
  homepage "https://github.com/scttfrdmn/prism"
  version "0.5.8"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.8/prism_0.5.8_darwin_x86_64.tar.gz"
      sha256 "2e8028f3ab5d03a6be6f0a0668e66d8d2038f3ccb07e2e40ba22820027a1b2d9"

      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.8/prism_0.5.8_darwin_arm64.tar.gz"
      sha256 "893eb004fc977fe5d324d6f5bbeb471bcc00090a3d7d6ff3b396dd9478e59a2d"

      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.8/prism_0.5.8_linux_x86_64.tar.gz"
      sha256 "1cd4e3c7a6164b40084117901febf71e607f7f6d9a02d698355ed0ba35b094f1"
      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.8/prism_0.5.8_linux_arm64.tar.gz"
      sha256 "0d08accf885c7b34e0142f79abdbfc612442c888bf44a55fbe860f98fa5ecd10"
      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
  end

  def caveats
    <<~EOS
      Prism has been installed!

      Command Line Interface (CLI):
        prism --help

      Terminal User Interface (TUI):
        prism tui

      Quick start:
        prism templates                           # List available templates
        prism launch <template-name> <instance>   # Launch a workstation

      The daemon (prismd) starts automatically when needed - no manual setup required!

      AWS credentials are required:
        aws configure

      Documentation: https://github.com/scttfrdmn/prism
    EOS
  end

  test do
    system "#{bin}/prism", "--version"
    system "#{bin}/prismd", "--version"
  end
end
