# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prism < Formula
  desc "CLI tool for launching pre-configured cloud workstations for academic research"
  homepage "https://github.com/scttfrdmn/prism"
  version "0.5.8"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.8/prism_0.5.8_darwin_x86_64.tar.gz"
      sha256 "13606729df8514e8b2a07182aa4b2f9be0a526a69c3389674184bbf06f2c786c"

      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.8/prism_0.5.8_darwin_arm64.tar.gz"
      sha256 "adb5e688f1e59b8549de05b478d43cd8010ef5342dbfb4a72c51df6eb0589c6c"

      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.8/prism_0.5.8_linux_x86_64.tar.gz"
      sha256 "9d29946d1653aa4e79b91c091241a31566cb036c696490ea5c93f0c5913f4b0a"
      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.8/prism_0.5.8_linux_arm64.tar.gz"
      sha256 "7f9c84416fb2dca57a378f703c0b033af3fdf7a42e9b30751f512ba5e66f2250"
      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
  end

  def caveats
    <<~EOS
      Prism has been installed!

      Command Line Interface (CLI):
        prism --help

      Terminal User Interface (TUI):
        prism tui

      Quick start:
        prism templates                           # List available templates
        prism launch <template-name> <instance>   # Launch a workstation

      The daemon (prismd) starts automatically when needed - no manual setup required!

      AWS credentials are required:
        aws configure

      Documentation: https://github.com/scttfrdmn/prism
    EOS
  end

  test do
    system "#{bin}/prism", "--version"
    system "#{bin}/prismd", "--version"
  end
end
