# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-jupyter" do
  name "aws-jupyter"
  desc "CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-jupyter"
  version "0.3.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-jupyter"

  on_macos do
    on_intel do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Darwin_x86_64.tar.gz"
      sha256 "08c2fde44f0a4b70c374c957a0ba9d844dd9855ae39f982582559e2a69f6bd95"
    end
    on_arm do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Darwin_arm64.tar.gz"
      sha256 "ff829a5dbc600fb69f56abd38268058a8dd21713ad00f1652b78286ad6958aa7"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Linux_x86_64.tar.gz"
      sha256 "e7aa3461bb613b2d85e413c151454bd15dd423612ac501cc25144f4c184787a8"
    end
    on_arm do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Linux_arm64.tar.gz"
      sha256 "16bc95ac663f8951938ba0848c46f874103f88cd4abfef2522add1c3e0f3479c"
    end
  end

  # No zap stanza required
end
