# This file was generated by GoReleaser. DO NOT EDIT.
cask "aws-jupyter" do
  name "aws-jupyter"
  desc "CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-jupyter"
  version "0.3.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aws-jupyter"

  on_macos do
    on_intel do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Darwin_x86_64.tar.gz"
      sha256 "7115d82b1b2ddc7db601ac984f465ec8cfab883e189c472f8b7fc23cd75c1f03"
    end
    on_arm do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Darwin_arm64.tar.gz"
      sha256 "dbda99a97391a2539c90d74316faa8f0b402590d5258e604f6e01efd0b2db2be"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Linux_x86_64.tar.gz"
      sha256 "77516f4def8e60b09f884fe84de192fca8988b1b9cd9974586118fa118ac8dd5"
    end
    on_arm do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v#{version}/aws-jupyter_Linux_arm64.tar.gz"
      sha256 "1a771f3611954159aa87b3fa6186567d2c39263ed8e346ffc6890f5bc8434931"
    end
  end

  # No zap stanza required
end
