# typed: false
# frozen_string_literal: true

# This file is maintained manually. Updates are generated by scripts/update-homebrew-formula.sh

class AwsJupyter < Formula
  desc "CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-jupyter"
  version "0.3.3"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v0.3.3/aws-jupyter_Darwin_x86_64.tar.gz"
      sha256 "39480996db9a1c4f34647761467d0853b10d69b246343c088e062803022f37d4"

      def install
        bin.install "aws-jupyter"
        pkgshare.install "environments"
      end
    end
    on_arm do
      url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v0.3.3/aws-jupyter_Darwin_arm64.tar.gz"
      sha256 "2ab8f2694bf6d808ee3032eb5165bbcdf7805faf0b9979e548395076eb587aee"

      def install
        bin.install "aws-jupyter"
        pkgshare.install "environments"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v0.3.3/aws-jupyter_Linux_x86_64.tar.gz"
        sha256 "0252e0cae609af41382d419363aab6243c1e7269e777a083d97f968544cc76f9"

        def install
          bin.install "aws-jupyter"
          pkgshare.install "environments"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/scttfrdmn/aws-jupyter/releases/download/v0.3.3/aws-jupyter_Linux_arm64.tar.gz"
        sha256 "f4180e530af09e0776d178e0686c6523ace4b59a75175465f2832040188410fa"

        def install
          bin.install "aws-jupyter"
          pkgshare.install "environments"
        end
      end
    end
  end

  test do
    system "#{bin}/aws-jupyter", "--version"
  end
end
