# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsVscode < Formula
  desc "CLI tool for launching VSCode Server instances on AWS EC2 Graviton processors (Beta)"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.7.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.1/aws-vscode_Darwin_x86_64.tar.gz"
      sha256 "4b32d83a1aed13084405ed1ea7c54803e707ba8667c003b7b756cb923782031c"

      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.1/aws-vscode_Darwin_arm64.tar.gz"
      sha256 "3b7af6dc7441c6ad538004a8412f1026e23fc17717ad198bbeba0dc9460ea145"

      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.1/aws-vscode_Linux_x86_64.tar.gz"
      sha256 "263e1a60262846ce90b4aa0929e9118029c2d71ddd0d3e4781e20aa4680f3866"
      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.1/aws-vscode_Linux_arm64.tar.gz"
      sha256 "07336b73365d84e90585773fdbfb7d090251ad6cc0616c8363adfe3c83de3b8c"
      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-vscode", "--version"
  end
end
