# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsJupyter < Formula
  desc "CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.1/aws-jupyter_Darwin_x86_64.tar.gz"
      sha256 "52a1ad5a7608378be5127fc976df9b311fe55b3ac6a13937fa80bae573b71d4c"

      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.1/aws-jupyter_Darwin_arm64.tar.gz"
      sha256 "a6a29662834d70f98d1f4ab5c3ac0b08b6189b328e5013622d7713b6dfdfcf58"

      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.1/aws-jupyter_Linux_x86_64.tar.gz"
      sha256 "508ac41d4a9a45c733e62e2e4dde6a23ced0bed8780eb1b9916c8764b8b6e8bd"
      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.1/aws-jupyter_Linux_arm64.tar.gz"
      sha256 "3efeb741cbd700af40492dd82f3cc4f996772eca59216167698fda95c3f4b128"
      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-jupyter", "--version"
  end
end
