# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsVscode < Formula
  desc "CLI tool for launching VSCode Server instances on AWS EC2 Graviton processors (Beta)"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.0/aws-vscode_Darwin_x86_64.tar.gz"
      sha256 "f9de8ba949e7ac61bcd7d0d6d3e29381c30ea059eed6c83b3e5ded4d5d12572a"

      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.0/aws-vscode_Darwin_arm64.tar.gz"
      sha256 "377ac09d16b788243fd3b41a202e2cd3d35be122a839dcbdb59b904f76bd68a5"

      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.0/aws-vscode_Linux_x86_64.tar.gz"
      sha256 "7e539557c9ec0e808ce630ee263c99786c4572103928197a3d0297206e0303f9"
      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.0/aws-vscode_Linux_arm64.tar.gz"
      sha256 "2658b95040dc0cb2f0f57feebd48430e22f2a85c318cd43ddf913331ef97aae9"
      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-vscode", "--version"
  end
end
