# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsVscode < Formula
  desc "CLI tool for launching VSCode Server instances on AWS EC2 Graviton processors (Beta)"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.1/aws-vscode_Darwin_x86_64.tar.gz"
      sha256 "573035953312202dcd7ad9b22d006ad66b6cc188c763d687b57165142820c5e8"

      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.1/aws-vscode_Darwin_arm64.tar.gz"
      sha256 "f32639b07cd2bc30c37bca192c7fb4b7d65c6c632d66d6d4800a0ed1309ebfc2"

      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.1/aws-vscode_Linux_x86_64.tar.gz"
      sha256 "48a041057452d3da6e2d98d621a3bf4f367ad0539efe4880850a05a5e651bf8e"
      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.1/aws-vscode_Linux_arm64.tar.gz"
      sha256 "c5c055beced56e2822afd3e83fee5a4d280e46a745b4c15f2925284486264c91"
      def install
        bin.install "aws-vscode"

        # Install environment templates
        pkgshare.install Dir["apps/vscode/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/vscode/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-vscode", "--version"
  end
end
