# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsRstudio < Formula
  desc "CLI tool for launching RStudio Server instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.7.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.0/aws-rstudio_Darwin_x86_64.tar.gz"
      sha256 "d4f7ce7cda75ad575a2a06efb5009f35626022c1f33381858ddd693383ed5198"

      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.0/aws-rstudio_Darwin_arm64.tar.gz"
      sha256 "2f623a94c20468d56a9e285fe5d02096045ee225306e30d77d77338a0ed9566f"

      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.0/aws-rstudio_Linux_x86_64.tar.gz"
      sha256 "4028a4ea75abe658030c8d165e5987b87c9ce7832e534b8cbed718ddb3ee7994"
      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.0/aws-rstudio_Linux_arm64.tar.gz"
      sha256 "ff7f194adaa42f864060ce35993b7dee790ea314eacc3f63a39308c79a32012d"
      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-rstudio", "--version"
  end
end
