# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsJupyter < Formula
  desc "CLI tool for launching Jupyter Lab instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.0/aws-jupyter_Darwin_x86_64.tar.gz"
      sha256 "95b4be8b6de9a012ac38bb0cfabbb8070850abf2e69452afd0f69a62e4597d45"

      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.0/aws-jupyter_Darwin_arm64.tar.gz"
      sha256 "ba2a2931026069fa0eb8d286db16cc1a5e5eef8982cb9545a08910ff2afca6dc"

      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.0/aws-jupyter_Linux_x86_64.tar.gz"
      sha256 "5f9e0a699751967129f70b05145ee79d3336537a75e715b7a8c480d267352f95"
      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.0/aws-jupyter_Linux_arm64.tar.gz"
      sha256 "24c61f7094caf2849ac607a70383661ca0a646489469498c0191b1dbb007dc22"
      def install
        bin.install "aws-jupyter"

        # Install environment templates
        pkgshare.install Dir["apps/jupyter/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/jupyter/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-jupyter", "--version"
  end
end
