# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsRstudio < Formula
  desc "CLI tool for launching RStudio Server instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.6.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.2/aws-rstudio_Darwin_x86_64.tar.gz"
      sha256 "0ffc935304cdac4fe90b6f154ddf40208bf852bdcca076ab04c297c20e80cb00"

      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.2/aws-rstudio_Darwin_arm64.tar.gz"
      sha256 "47599098d2d26cff4f27a83c3a9ba96de241596a34127a3bdcf24ecedb4b1470"

      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.2/aws-rstudio_Linux_x86_64.tar.gz"
      sha256 "66ddedc74ff6a84beef8601937d23d5c10a07832a7e40463690d19e7133dcadf"
      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.6.2/aws-rstudio_Linux_arm64.tar.gz"
      sha256 "19bba3814ef47cfeae33d39bc409f4e827e97ba69fea202b1e1733dba98378d8"
      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-rstudio", "--version"
  end
end
