# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsRstudio < Formula
  desc "CLI tool for launching RStudio Server instances on AWS EC2 Graviton processors"
  homepage "https://github.com/scttfrdmn/aws-ide"
  version "0.7.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.1/aws-rstudio_Darwin_x86_64.tar.gz"
      sha256 "3a8fae83ad8ee8f08cf50fc28e7f05fd52aaef9a274be09fd7f8006453f8c180"

      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.1/aws-rstudio_Darwin_arm64.tar.gz"
      sha256 "b9d55885fc7c90a75ff9e4a32ebf67d772417c629a13aa7f940a705bdd82942e"

      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.1/aws-rstudio_Linux_x86_64.tar.gz"
      sha256 "0af1342f89956e998f26a08298c0ff38981b27dab888d44fa23b9f131b4a88de"
      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/aws-ide/releases/download/v0.7.1/aws-rstudio_Linux_arm64.tar.gz"
      sha256 "ac552daaa8538da9fca2395608ebfc26288b5f3ac825b3b83f4675e56e61275e"
      def install
        bin.install "aws-rstudio"

        # Install environment templates
        pkgshare.install Dir["apps/rstudio/environments/*.yaml"]
        (pkgshare/"environments").mkpath
        Dir["apps/rstudio/environments/*.yaml"].each do |env|
          (pkgshare/"environments").install env
        end
      end
    end
  end

  test do
    system "#{bin}/aws-rstudio", "--version"
  end
end
