# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudworkstation < Formula
  desc "CLI tool for launching pre-configured cloud workstations for academic research"
  homepage "https://github.com/scttfrdmn/cloudworkstation"
  version "0.5.4"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.4/cloudworkstation_0.5.4_darwin_x86_64.tar.gz"
      sha256 "4a051cea2193290a8d15822f93acb59f4ae07bbcdb01a9623de51955938d2ff3"

      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.4/cloudworkstation_0.5.4_darwin_arm64.tar.gz"
      sha256 "9b96e61bda8da13989201b490ecab8365301fba42200fb65a80e8f8889f92912"

      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.4/cloudworkstation_0.5.4_linux_x86_64.tar.gz"
      sha256 "7faf4dc93c37071e4de2d81a53904ff6c90ecef286fd0929a5878374ad8c6881"
      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/cloudworkstation/releases/download/v0.5.4/cloudworkstation_0.5.4_linux_arm64.tar.gz"
      sha256 "efab48a37b349a1a74d73ef3e3c2d132a0554d6d440bf6053b9a5b9f615fbd40"
      def install
        bin.install "cws"
        bin.install "cwsd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"cloudworkstation").install "templates"

        # Create config directory
        (etc/"cloudworkstation").mkpath
      end
    end
  end

  def caveats
    <<~EOS
      CloudWorkstation has been installed!

      Command Line Interface (CLI):
        cws --help

      Terminal User Interface (TUI):
        cws tui

      Quick start:
        cws templates                           # List available templates
        cws launch <template-name> <instance>   # Launch a workstation

      The daemon (cwsd) starts automatically when needed - no manual setup required!

      AWS credentials are required:
        aws configure

      Documentation: https://github.com/scttfrdmn/cloudworkstation
    EOS
  end

  test do
    system "#{bin}/cws", "--version"
    system "#{bin}/cwsd", "--version"
  end
end
