# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prism < Formula
  desc "CLI tool for launching pre-configured cloud workstations for academic research"
  homepage "https://github.com/scttfrdmn/prism"
  version "0.5.15"
  license "MIT"

  depends_on "go" => :build

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.15/prism_0.5.15_darwin_x86_64.tar.gz"
      sha256 "69b4417d11923adf58522325e4a2d2df51cc7447001929564b4bf4a8cc2eb9e8"

      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.15/prism_0.5.15_darwin_arm64.tar.gz"
      sha256 "90fe31c69757a3765626f2cc8c9822daa42c6f6aa962ec12de2a70f3fd026d8f"

      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.15/prism_0.5.15_linux_x86_64.tar.gz"
      sha256 "0509a40284bb1f890b124f0f3d7051ea80c20ccbd5294c2e56b87e7db364ef9a"
      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/scttfrdmn/prism/releases/download/v0.5.15/prism_0.5.15_linux_arm64.tar.gz"
      sha256 "d7819cfc809fc19a6307fbb74a530516175a73e0f5ed9a219610188f7cd95edf"
      def install
        bin.install "prism"
        bin.install "prismd"

        # Install documentation
        doc.install "README.md"
        doc.install "CHANGELOG.md"

        # Install templates
        (share/"prism").install "templates"

        # Create config directory
        (etc/"prism").mkpath
      end
    end
  end

  def caveats
    <<~EOS
      Prism has been installed!

      Command Line Interface (CLI):
        prism --help

      Terminal User Interface (TUI):
        prism tui

      Quick start:
        prism templates                           # List available templates
        prism launch <template-name> <instance>   # Launch a workstation

      The daemon (prismd) starts automatically when needed - no manual setup required!

      AWS credentials are required:
        aws configure

      Documentation: https://github.com/scttfrdmn/prism
    EOS
  end

  test do
    system "#{bin}/prism", "--version"
    system "#{bin}/prismd", "--version"
  end
end
